version: "3.4"

services:
    nginx_sipac:
        image: nexus.prod.uci.cu/nginx:alpine
        ports:
            - "80:80"
            - "443:443"  
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/default-nginx.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx.pem:/etc/ssl/certs/nginx.pem
            - ./conf/nginx.key:/etc/ssl/private/nginx.key
        links:
            - apache_sipac:apache_sipac
        container_name: nginx_proxy
        working_dir: /etc/nginx/
        restart: always
        
    php_sipac:
        image: nexus.prod.uci.cu/rmolinet/sipac-php-alpine:3.0
        expose:
            - "9004"
        extra_hosts:
            - "dockerhost:172.17.0.1"
        volumes:
            - ../Docker-SIPAC/conf/sipac_2.4:/usr/local/apache2/htdocs/sipac_2.4
            - ./conf/php.ini:/usr/local/etc/php/php.ini
            #- ./conf/kcachegrind_files:/usr/local/reportes_kcachegrind
        container_name: php5_fpm
        working_dir: /usr/local/apache2/htdocs/
        restart: always
        
    apache_sipac:
        image: nexus.prod.uci.cu/httpd:alpine
        links:
            - php_sipac:php_sipac
        volumes:
            - ../Docker-SIPAC/conf/sipac_2.4:/usr/local/apache2/htdocs/sipac_2.4
            - ./conf/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./conf/apache2/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
            - ./logs/apache/:/usr/local/apache2/logs/
            - ./conf/nginx.pem:/usr/local/apache2/conf/server.crt
            - ./conf/nginx.key:/usr/local/apache2/conf/server.key
        working_dir: /usr/local/apache2/htdocs/
        restart: always
